name: Build and Push Docker Image to Repo

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build Docker Image
        run: docker build -t ${{ vars.DOCKER_NAME }}/deploy:latest .

      - name: Push Docker Image
        run: docker push ${{ vars.DOCKER_NAME }}/deploy:latest

      - name: Run Docker Container (for testing)
        run: docker run -d -p 3000:3000 ${{ vars.DOCKER_NAME }}/deploy:latest

      - name: List out all Files and Directory
        run: ls


  deploy-to-aws:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to AWS EC2 via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ vars.AWS_EC2_USER }}  
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          script: |
            sudo usermod -aG docker $USER
            newgrp docker
            docker pull ${{ vars.DOCKER_NAME }}/deploy:latest
            docker stop deploy || true
            docker rm deploy || true
            docker run -d -p 3000:3000 --name deploy ${{ vars.DOCKER_NAME }}/deploy:latest